FROM ros:humble-ros-base-jammy

WORKDIR /jetson_ws

ENV DEBIAN_FRONTEND=noninteractive
ENV USERNAME=jetson
ENV HOME=/home/$USERNAME

# ENV RMW_IMPLEMENTATION=rmw_fastrtps_cpp

RUN apt-get update || true && apt-get install -y curl 

# RUN curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg && \
#     echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" > /etc/apt/sources.list.d/ros2.list 
    
RUN rm -f /etc/apt/sources.list.d/ros2.list

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    i2c-tools \ 
    libi2c-dev \
    python3-pip \
    && rm -rf /var/lib/apt/lists/* \
    && pip3 install -U setuptools==58.2.0

COPY ./src ./src

# RUN rosdep update --rosdistro humble && \ 
#     ROS_OS_OVERRIDE=ubuntu:jammy rosdep install --from-paths src --ignore-src -y \
#     --rosdistro humble \
#     --skip-keys "gazebo_ros gazebo_ros_pkgs gazebo_plugins gz_ros2_control gazebo_ros2_control ros_gz ros_gz_sim ros_gz_bridge ament_pep257 geometry_msgs ament_cmake sensor_msgs"

RUN if [ ! -f /etc/ros/rosdep/sources.list.d/20-default.list ]; then rosdep init; fi && \
    rosdep update --rosdistro humble \
    --skip-keys "gazebo_ros gazebo_ros_pkgs gazebo_plugins gz_ros2_control gazebo_ros2_control ros_gz ros_gz_sim ros_gz_bridge ament_pep257 geometry_msgs ament_cmake sensor_msgs"

RUN rm -rf build log install

RUN echo 'source /opt/ros/humble/setup.bash' >> /etc/bash.bashrc && \
    echo 'if [ -f /jetson_ws/install/setup.bash ]; then source /jetson_ws/install/setup.bash; fi' >> /etc/bash.bashrc

