twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic:   "/teleop/cmd_vel"
        msg_type: "geometry_msgs/msg/TwistStamped" # <- KLUCZOWE
        timeout: 0.5
        priority: 120
      ittc:
        topic:   "/ittc/cmd_vel"
        msg_type: "geometry_msgs/msg/TwistStamped" # <- KLUCZOWE
        timeout: 0.5
        priority: 100

      pursuit:
        topic:   "/pursuit/cmd_vel"
        msg_type: "geometry_msgs/msg/TwistStamped" # <- KLUCZOWE
        timeout: 0.5
        priority: 80

      ftg:
        topic:   "/ftg/cmd_vel"
        msg_type: "geometry_msgs/msg/TwistStamped" # <- KLUCZOWE
        timeout: 0.5
        priority: 50

    # locks: {}